root: .
search_paths:
  - $venv
  - lib
  - src
  - .
entries:
  - src/main.py
  - $venv/IPython/__main__.py
  - $venv/streamlit/__main__.py
ignores:
  - matplotlib
  - numpy
  - pandas
export:
  source: $venv
  target: dist/minideps
